// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "5.4.0-beta.0-294-g285eb71db-dirty"
#define MICROPY_GIT_HASH "285eb71db-dirty"
#define MICROPY_BUILD_DATE "2021-05-16"
#define MICROPY_VERSION_MAJOR (5)
#define MICROPY_VERSION_MINOR (4)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_STRING "5.4.0"
#define MICROPY_FULL_VERSION_INFO ("Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME)
